MIDlet-Vendor:AJGames
MIDlet-Version:1.0
Manifest-Version:1.0
Created-By:1.4.2_02 (Sun Microsystems Inc.)
MicroEdition-Configuration:CLDC-1.0
MIDlet-Name:Mario MIDP2
MIDlet-1:Mariomp2, , ajmario.SpriteTest
MicroEdition-Profile:MIDP-2.0
