MIDlet-Vendor:Gameloft SA
MIDlet-Version:1.6.2
Manifest-Version:1.0
MIDlet-Icon:/icon.png
Created-By:1.4.2 (Sun Microsystems Inc.)
MicroEdition-Configuration:CLDC-1.0
MIDlet-Name:Harry Potter TDH2 VH By Sykeo99
MIDlet-1:Harry Potter TDH2 VH By Sykeo99, /icon.png, GloftHARR
SEMC-Screen-Size:240,320
MicroEdition-Profile:MIDP-2.0
